### ISSUE TITLE
Aurora snapshots not being exported  to s3 bucket.

### ISSUE THREAD

**Issue by collisiondetection** [aws-samples/rds-snapshot-export-to-s3-pipeline#14]
Hi, @michaelmoussa  I can not see any Aurora  snapshots being exported to the s3 bucket

I have the correct variables set in the cdk file
I have performed the test in the Lambda console. 
I can see system / automatic snapshots occurring in the RDS console

What else can I try? Is this script still working for Aurora databases?

**Comment by michaelmoussa** [comment]
This should be addressed by #12. Please try again with the new version and feel free to re-open this if the issue persists.
