### ISSUE TITLE
Error on lambda execution

### ISSUE THREAD

**Issue by dragosamarie** [aws-samples/rds-snapshot-export-to-s3-pipeline#7]
Hello all

Error still present

[ERROR] ClientError: An error occurred (InvalidParameterValue) when calling the StartExportTask operation: The parameter ExportTaskIdentifier is not a valid identifier. Identifiers must begin with a letter; must contain only ASCII letters, digits, and hyphens; and must not end with a hyphen or contain two consecutive hyphens.
Traceback (most recent call last):
  File "/var/task/main.py", line 44, in handler
    response = boto3.client("rds").start_export_task(
  File "/var/runtime/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)END RequestId: fc8d8812-bafc-4d43-a634-ecc7de52a9ed
REPORT RequestId: fc8d8812-bafc-4d43-a634-ecc7de52a9ed	Duration: 1771.77 ms	Billed Duration: 1800 ms	Memory Size: 128 MB	Max Memory Used: 75 MB	Init Duration: 262.20 ms

**Comment by dragosamarie** [comment]
Found issue - caused by snapshots name, I had to change code from slice [4:28] and not [4:27] as slice after 27 was "-"

**Comment by michaelmoussa** [comment]
Thanks for raising this issue, @dragosamarie! I've pushed https://github.com/aws-samples/rds-snapshot-export-to-s3-pipeline/commit/227a9c66453495229434effa42db72363e834cd1 as a fix for anybody else who might have ended up running into it.

**Comment by dragosamarie** [comment]
Great. Thanks
