### ISSUE TITLE
"the new key policy will not allow you to update the key policy in the future."

### ISSUE THREAD

**Issue by pedrozasantaigo** [aws-samples/rds-snapshot-export-to-s3-pipeline#8]
im getting this message when run 'npm run cdk deploy', when CloudFormation is creating AWS::KMS::Key  SnapshotExportEncryptionKey

**Comment by michaelmoussa** [comment]
Hi @pedrozasantaigo - are you still having this issue?

If so, I recommend checking to ensure that the IAM user and/or role that you're using to execute `npm run cdk deploy` has permission to make the `CreateKey` and `PutKeyPolicy` API calls. What's happening here most likely is that while the key policy itself doesn't _prevent_ your IAM Principal from updating the key policy, the Principal's IAM policy isn't explicitly _allowing_ it to do so.

Please feel free to re-open this if you're still experiencing this issue or if the suggestion above is unclear.
